### ISSUE TITLE
Criar relatório

### ISSUE THREAD

**Issue by LeonardoVieiraNunes** [LeonardoVieiraNunes/grafo-nao-orientado-e-valorado#6]

**Comment by MatheusFBBueno** [comment]
Link para relatório:
https://docs.google.com/document/d/1lkBbQZjLo47PT3WeKfR7DI92vcp4fdmgFSWLMMtY5QY/edit?usp=sharing

Ainda falta descrição de algoritmo de kruskal e dúvida sobre algoritmo de CFC, incluir explicação sobre implementação de grafos direcionados?
